function Tt = ThrusterVector(in1,in2)
%THRUSTERVECTOR
%    TT = THRUSTERVECTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Oct-2021 20:39:52

d_T1 = in1(:,1);
d_T2 = in1(:,2);
d_T3 = in1(:,3);
epsilon1 = in2(:,2);
epsilon2 = in2(:,3);
epsilon3 = in2(:,4);
eta = in2(:,1);
t2 = epsilon1.^2;
t3 = epsilon2.^2;
t4 = epsilon1.*epsilon3.*2.0;
t5 = epsilon2.*epsilon3.*2.0;
t6 = epsilon1.*eta.*2.0;
t7 = epsilon2.*eta.*2.0;
t8 = t2.*2.0;
t9 = t3.*2.0;
t10 = -t6;
t11 = t4+t7;
t12 = t5+t10;
t13 = t8+t9-1.0;
Tt = [-t11;-t5+t6;t13;d_T2.*t13+d_T3.*t12;-d_T1.*t13-d_T3.*t11;-d_T1.*t12+d_T2.*t11];
