function Tt = ThrusterVector(in1,in2,in3)
%ThrusterVector
%    Tt = ThrusterVector(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Jul-2022 16:58:54

RG1 = in3(:,1);
RG2 = in3(:,2);
RG3 = in3(:,3);
d_T1 = in1(:,1);
d_T2 = in1(:,2);
d_T3 = in1(:,3);
epsilon1 = in2(:,2);
epsilon2 = in2(:,3);
epsilon3 = in2(:,4);
eta = in2(:,1);
t2 = epsilon1.^2;
t3 = epsilon2.^2;
t4 = epsilon1.*epsilon3.*2.0;
t5 = epsilon2.*epsilon3.*2.0;
t6 = epsilon1.*eta.*2.0;
t7 = epsilon2.*eta.*2.0;
t8 = -d_T1;
t9 = -d_T2;
t10 = -d_T3;
t11 = t2.*2.0;
t12 = t3.*2.0;
t13 = -t6;
t14 = RG1+t8;
t15 = RG2+t9;
t16 = RG3+t10;
t17 = t4+t7;
t18 = t5+t13;
t19 = t11+t12-1.0;
Tt = [-t17;-t5+t6;t19;-t15.*t19-t16.*t18;t14.*t19+t16.*t17;t14.*t18-t15.*t17];
