%% Search for a specified operating point for the model - AUV_Model.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.8 and Simulink Control Design (TM) 5.5.
%
% Generated on: 12-Oct-2020 11:30:01

%% Specify the model name
model = 'AUV_Model';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - AUV_Model/Plant and Environment Model/Dynamics solver/6DOF (Euler Angles)/Calculate DCM & Euler Angles/phi theta psi
% - Default model initial conditions are used to initialize optimization.

% State (2) - AUV_Model/Plant and Environment Model/Dynamics solver/6DOF (Euler Angles)/p,q,r
% - Default model initial conditions are used to initialize optimization.

% State (3) - AUV_Model/Plant and Environment Model/Dynamics solver/6DOF (Euler Angles)/ub,vb,wb
% - Default model initial conditions are used to initialize optimization.

% State (4) - AUV_Model/Plant and Environment Model/Dynamics solver/6DOF (Euler Angles)/xe,ye,ze
% - Default model initial conditions are used to initialize optimization.

% State (5) - AUV_Model/Plant and Environment Model/Propulsion Forces & Moments/Input commands to Thrust/PWM Signals to Thrust /T200 Transfer Function
% - Default model initial conditions are used to initialize optimization.

% State (6) - AUV_Model/Plant and Environment Model/Propulsion Forces & Moments/Input commands to Thrust/PWM Signals to Thrust /T200 Transfer Function1
% - Default model initial conditions are used to initialize optimization.

% State (7) - AUV_Model/Plant and Environment Model/Propulsion Forces & Moments/Input commands to Thrust/PWM Signals to Thrust /T200 Transfer Function2
% - Default model initial conditions are used to initialize optimization.

% State (8) - AUV_Model/Plant and Environment Model/Propulsion Forces & Moments/Input commands to Thrust/PWM Signals to Thrust /T200 Transfer Function3
% - Default model initial conditions are used to initialize optimization.

% State (9) - AUV_Model/Plant and Environment Model/Propulsion Forces & Moments/Input commands to Thrust/PWM Signals to Thrust /T200 Transfer Function4
% - Default model initial conditions are used to initialize optimization.

% State (10) - AUV_Model/Plant and Environment Model/Propulsion Forces & Moments/Input commands to Thrust/PWM Signals to Thrust /T200 Transfer Function5
% - Default model initial conditions are used to initialize optimization.

% State (11) - AUV_Model/Plant and Environment Model/Propulsion Forces & Moments/Input commands to Thrust/PWM Signals to Thrust /T200 Transfer Function6
% - Default model initial conditions are used to initialize optimization.

% State (12) - AUV_Model/Plant and Environment Model/Propulsion Forces & Moments/Input commands to Thrust/PWM Signals to Thrust /T200 Transfer Function7
% - Default model initial conditions are used to initialize optimization.

% State (13) - AUV_Model/Position Controller/MPC Controller/MPC/last_mv
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);
