function StateEQUc = EKF_States_Eq(in1,in2)
%EKF_STATES_EQ
%    STATEEQUC = EKF_STATES_EQ(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Jul-2021 12:47:13

V_x = in1(1,:);
V_y = in1(2,:);
V_z = in1(3,:);
a_x = in1(4,:);
a_y = in1(5,:);
a_z = in1(6,:);
omega1 = in2(1,:);
omega2 = in2(2,:);
omega3 = in2(3,:);
omega4 = in2(4,:);
omega5 = in2(5,:);
omega6 = in2(6,:);
StateEQUc = [V_x+a_x./1.0e+2+omega1./4.0e+4;V_y+a_y./1.0e+2+omega2./4.0e+4;V_z+a_z./1.0e+2+omega3./4.0e+4;a_x+omega4./6.25e+2;a_y+omega5./6.25e+2;a_z+omega6./6.25e+2];
