control:
  simulation: 
    model_name: 'auv8'
    reference_frame: 'world'

  physics:
    mass: 33.95            # Kg
    volume: 0.037          # m^3
    rho: 998               # Kg / m^3
    g: 9.81                # m / s^2
    dvlCenterDist: 0.1435  # m
    height: 0.3            # m
    inertia: 
      - [ 1.5, 0.001, 0.01 ]  # Ixx Ixy Ixz
      - [ 0.002, 1.8, 0.005 ] # Iyx Iyy Iyz
      - [ 0.01, 0.005, 1.45 ] # Izx Izy Izz

    RG: [ 0.001, -0.003, 0.027 ] # m (x, y, z)

    RB: [ 0.0, 0.0, -0.1 ] # m (x, y, z)

    CDL: [ 45, 60, 70, 10, 7, 15 ] # (x, y, z, roll, pitch, yaw)

    CDQ: [ 1.17, 0.82, 0.756, 0.167, 0.1, 0.102 ] # (x, y, z, roll, pitch, yaw)

    AF: [ 0.12, 0.22, 0.292 ] # m^2

    AddedMass: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ] # Kg

  thrusters:
    ThrusterConfig:
        #    x      y      z    yaw  pitch  roll
      - [  0.292, 0.173, 0.082,-45.0,-90.0, 0.0 ] # T1
      - [ -0.292, 0.173, 0.082, 45.0,-90.0, 0.0 ] # T2
      - [ -0.292,-0.173, 0.082,-45.0,-90.0, 0.0 ] # T3
      - [  0.292,-0.173, 0.082, 45.0,-90.0, 0.0 ] # T4
      - [  0.181, 0.159, 0.082,  0.0,  0.0, 0.0 ] # T5
      - [ -0.181, 0.159, 0.082,  0.0,180.0, 0.0 ] # T6
      - [ -0.181,-0.159, 0.082,  0.0,  0.0, 0.0 ] # T7
      - [  0.181,-0.159, 0.082,  0.0,180.0, 0.0 ] # T8
  mpc:
    nx: 13 
    ny: 13
    nu: 8
    Ts: 0.25  # sec
    p: 4
    m: 2
    tmax: 29
    tmin: -24
    gains:
      default:
        OV: [ 70, 60, 70, 50, 50, 50, 50, 0, 0, 0, 0, 0, 0 ]
        MV: [ 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 ]
        MVR: [ 0.1, 0.1, 0.1, 0.1, 0.3, 0.3, 0.3, 0.3 ]
      c10:
        OV: [ 70, 60, 70, 50, 50, 50, 50, 0, 0, 0, 0, 0, 0 ]
        MV: [ 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 ]
        MVR: [ 0.1, 0.1, 0.1, 0.1, 0.3, 0.3, 0.3, 0.3 ]
      c19:
        OV: [ 0, 0, 0, 0, 0, 0, 0, 70, 60, 70, 50, 50, 50]
        MV: [ 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 ]
        MVR: [ 0.1, 0.1, 0.1, 0.1, 0.3, 0.3, 0.3, 0.3 ]
