# Control parameters

#Trajectory configuration
/proc_planner/low_speed/maximum_acceleration : 0.05   # m/s^2
/proc_planner/low_speed/maximum_velocity : 0.2         # m/s
/proc_planner/low_speed/maximum_angular_rate : 0.3     # rad/s

/proc_planner/normal_speed/maximum_acceleration : 0.1 # m/s^2
/proc_planner/normal_speed/maximum_velocity : 0.5      # m/s
/proc_planner/normal_speed/maximum_angular_rate : 0.5  # rad/s

/proc_planner/high_speed/maximum_acceleration : 0.15  # m/s^2
/proc_planner/high_speed/maximum_velocity : 0.8        # m/s
/proc_planner/high_speed/maximum_angular_rate : 0.8    # rad/s