//
// Created by olavoie on 5/1/18.
//

#ifndef CONTROL_LIBRARY_CONTROLTYPE_H
#define CONTROL_LIBRARY_CONTROLTYPE_H

const int CARTESIAN_SPACE   = 6;
const int POSITION_SPACE    = 3;
const int ORIENTATION_SPACE = 3;

#endif //CONTROL_LIBRARY_CONTROLTYPE_H
