function out1 = hydroAngles2pinger(in1,in2,in3,in4,rho)
%hydroAngles2pinger
%    OUT1 = hydroAngles2pinger(IN1,IN2,IN3,IN4,RHO)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    03-Mar-2022 15:38:27

d_x = in3(1,:);
d_y = in3(2,:);
d_z = in3(3,:);
epsilon1 = in2(:,2);
epsilon2 = in2(:,3);
epsilon3 = in2(:,4);
eta = in2(:,1);
phi = in4(:,1);
ps_x = in1(1,:);
ps_y = in1(2,:);
ps_z = in1(3,:);
theta = in4(:,2);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = epsilon1.^2;
t7 = epsilon2.^2;
t8 = epsilon3.^2;
t9 = epsilon1.*epsilon2.*2.0;
t10 = epsilon1.*epsilon3.*2.0;
t11 = epsilon2.*epsilon3.*2.0;
t12 = epsilon1.*eta.*2.0;
t13 = epsilon2.*eta.*2.0;
t14 = epsilon3.*eta.*2.0;
t15 = t6.*2.0;
t16 = t7.*2.0;
t17 = t8.*2.0;
t18 = -t12;
t19 = -t13;
t20 = -t14;
t21 = t9+t14;
t22 = t10+t13;
t23 = t11+t12;
t24 = t9+t20;
t25 = t10+t19;
t26 = t11+t18;
t27 = t15+t16-1.0;
t28 = t15+t17-1.0;
t29 = t16+t17-1.0;
out1 = [ps_x-d_x.*t29+d_y.*t24+d_z.*t22+rho.*t3.*t22+rho.*t4.*t5.*t24-rho.*t2.*t5.*t29;ps_y+d_x.*t21-d_y.*t28+d_z.*t26+rho.*t3.*t26+rho.*t2.*t5.*t21-rho.*t4.*t5.*t28;ps_z+d_x.*t25+d_y.*t23-d_z.*t27-rho.*t3.*t27+rho.*t2.*t5.*t25+rho.*t4.*t5.*t23];
