function out1 = rhoEstimator(in1,in2,in3,in4,in5,in6,in7)
%rhoEstimator
%    OUT1 = rhoEstimator(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    03-Mar-2022 15:38:28

d_x = in7(1,:);
d_y = in7(2,:);
d_z = in7(3,:);
epsilon1 = in2(:,2);
epsilon2 = in2(:,3);
epsilon3 = in2(:,4);
epsilon_k1 = in5(:,2);
epsilon_k2 = in5(:,3);
epsilon_k3 = in5(:,4);
eta = in2(:,1);
eta_k = in5(:,1);
phi = in3(:,1);
phi_k = in6(:,1);
ps_y = in1(2,:);
ps_yk = in4(2,:);
theta = in3(:,2);
theta_k = in6(:,2);
t2 = sin(theta);
t3 = sin(theta_k);
t4 = epsilon1.^2;
t5 = epsilon3.^2;
t6 = epsilon_k1.^2;
t7 = epsilon_k3.^2;
t8 = epsilon1.*epsilon2.*2.0;
t9 = epsilon2.*epsilon3.*2.0;
t10 = epsilon_k1.*epsilon_k2.*2.0;
t11 = epsilon_k2.*epsilon_k3.*2.0;
t12 = epsilon1.*eta.*2.0;
t13 = epsilon3.*eta.*2.0;
t14 = epsilon_k1.*eta_k.*2.0;
t15 = epsilon_k3.*eta_k.*2.0;
t16 = t4.*2.0;
t17 = t5.*2.0;
t18 = t6.*2.0;
t19 = t7.*2.0;
t20 = -t12;
t21 = -t14;
t22 = t8+t13;
t23 = t10+t15;
t24 = t9+t20;
t25 = t11+t21;
t26 = t16+t17-1.0;
t27 = t18+t19-1.0;
out1 = -(ps_y-ps_yk+d_x.*t22-d_x.*t23-d_y.*t26+d_y.*t27+d_z.*t24-d_z.*t25)./(t24.*cos(theta)-t25.*cos(theta_k)+t2.*t22.*cos(phi)-t3.*t23.*cos(phi_k)-t2.*t26.*sin(phi)+t3.*t27.*sin(phi_k));
